name: lil-lisa-web
channels:
  - conda-forge
dependencies:
  - make=4.2.1
  - python=3.11.9
  - pip=24.2
  - pip:
    - python-fasthtml
    - isort==5.12.0
    - black==23.1.0
    - flake8==6.0.0
    - pylint==2.16.1
    - mypy==1.0.0
    - bandit[toml]==1.7.4
    - requests==2.31.0
    - pyjwt==2.8.0
    - uvicorn>=0.29
