name: LilLisa_Server
channels:
  - conda-forge
dependencies:
  - make=4.2.1
  - python=3.11.9
  - pip=22.3.1
  - pip:
    - isort==5.12.0
    - black==23.1.0
    - flake8==6.0.0
    - pylint==2.16.1
    - mypy==1.0.0
    - bandit[toml]==1.7.4
    - fastapi==0.103.0
    - pyjwt==2.8.0
    - python-dotenv==1.0.0
    - boto3==1.34.147
    - lancedb==0.10.2
    - llama-index==0.10.58
    - llama-index-vector-stores-lancedb==0.1.7
    - mangum==0.17.0
    - openai==1.37.0
    - sentence-transformers==3.0.1
    - speedict==0.3.12
    - tiktoken==0.7.0
    - uvicorn==0.20.0